apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.secret_name }}"
    labels:
        app: {{ template "ipu-policy-service.fullname" . }}
type: Opaque
stringData:
    DROPBOX_APP_LOCATION: "{{ .Values.dropbox_app_location }}"
    DROPBOX_ACCESS_TOKEN: "{{ .Values.dropbox_access_token }}"
    DROPBOX_APP_LINK: "{{ .Values.dropbox_app_link }}"
    IPU_EMAIL_SERVICE_HOST: "{{ .Values.ipu_email_service_host }}"
    IPU_DB_USER: "{{ .Values.ipu_db_user }}"
    IPU_DB_PASSWORD: "{{ .Values.ipu_db_password }}"
    DATABASE_HOST: "{{ .Values.database_host }}"
    DATABASE_PORT: "{{ .Values.database_port }}"
    IPU_DB_HOST: "{{ .Values.ipu_db_host }}"
    IPU_DB_PORT: "{{ .Values.ipu_db_port }}"
    IPU_DATABASE: "{{ .Values.ipu_database }}"
    ENV_NAME: "{{ .Values.env_name }}"
    DATABASE_DATABASE: "{{ .Values.database_database }}"
    DATABASE_USER: "{{ .Values.database_user }}"
    DATABASE_PASSWORD: "{{ .Values.database_password }}"
    IPU_DB_HOST: "{{ .Values.ipu_db_host }}"
    IPU_DB_PORT: "{{ .Values.ipu_db_port }}"
    DATABASE_HOST: "{{ .Values.database_host }}"
    DATABASE_PORT: "{{ .Values.database_port }}"
    ONE_DRIVE_API_IPU_CLIENT_ID: "{{ .Values.one_drive_api_ipu_client_id }}"
    ONE_DRIVE_API_IPU_CLIENT_SECRET: "{{ .Values.one_drive_api_ipu_client_secret }}"
    ONE_DRIVE_API_IPU_USER_NAME: "{{ .Values.one_drive_api_ipu_user_name }}"
    ONE_DRIVE_API_IPU_PASSWORD: "{{ .Values.one_drive_api_ipu_password }}"
    ONE_DRIVE_API_IPU_SCOPE: "{{ .Values.one_drive_api_ipu_scope }}"
    TENANT_ID: "{{ .Values.tenant_id }}"
    SHAREPOINT_APP_LOCATION: "{{ .Values.sharepoint_app_location }}"
    SHAREPOINT_APP_LINK: "{{ .Values.sharepoint_app_link }}"
    ONE_DRIVE_AMPS_IPU_SITE_ID: "{{ .Values.one_drive_amps_ipu_site_id }}"
    ONE_DRIVE_AMPS_IPU_DRIVE_ID: "{{ .Values.one_drive_amps_ipu_drive_id }}"